### PR TITLE
Fix packge.json file/main content

### PR DESCRIPTION
**Pull request by SBoudrias**
There's no main file, so we're not setting it.

### CODE REVIEW

**Comment by boneskull** [comment]
@SBoudrias thanks!

**Comment by boneskull** [comment]
@SBoudrias sorry, but it still isn't working:

``` shell
boneskull at lectroid in ~/projects/boneskull/generator-boneskull on master
$ npm install -g boneskull/generator-boneskull#master

> buffertools@2.1.3 install /usr/local/lib/node_modules/generator-boneskull/node_modules/slug/node_modules/unicode/node_modules/bufferstream/node_modules/buffertools
> node-gyp rebuild

  CXX(target) Release/obj.target/buffertools/buffertools.o
  SOLINK_MODULE(target) Release/buffertools.node

> unicode@0.6.1 postinstall /usr/local/lib/node_modules/generator-boneskull/node_modules/slug/node_modules/unicode
> node install.js

try to read file /usr/share/unicode/UnicodeData.txt …
/usr/share/unicode/UnicodeData.txt not found.
try to read file /usr/share/unicode-data/UnicodeData.txt …
/usr/share/unicode-data/UnicodeData.txt not found.
try to read file UnicodeData.txt …
UnicodeData.txt not found.
try to download …
GET unicode.org:80/Public/UNIDATA/UnicodeData.txt
fetching …
saving data as Cc.js …
saving data as Zs.js …
saving data as Po.js …
saving data as Sc.js …
saving data as Ps.js …
saving data as Pe.js …
saving data as Sm.js …
saving data as Pd.js …
saving data as Nd.js …
saving data as Lu.js …
saving data as Sk.js …
saving data as Pc.js …
saving data as Ll.js …
saving data as So.js …
saving data as Lo.js …
saving data as Pi.js …
saving data as Cf.js …
saving data as No.js …
saving data as Pf.js …
saving data as Lt.js …
saving data as Lm.js …
saving data as Mn.js …
saving data as Me.js …
saving data as Mc.js …
saving data as Nl.js …
saving data as Zl.js …
saving data as Zp.js …
saving data as Cs.js …
saving data as Co.js …
done.

> spawn-sync@1.0.13 postinstall /usr/local/lib/node_modules/generator-boneskull/node_modules/yeoman-generator/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

generator-boneskull@0.4.0 /usr/local/lib/node_modules/generator-boneskull
├── humanize-url@1.0.1 (strip-url-auth@1.0.1)
├── chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── normalize-url@1.3.0 (prepend-http@1.0.2, object-assign@3.0.0, sort-keys@1.1.1, query-string@2.4.0)
├── yosay@1.0.5 (ansi-regex@1.1.1, ansi-styles@2.1.0, word-wrap@1.1.0, strip-ansi@2.0.1, pad-component@0.0.1, taketalk@1.0.0, minimist@1.1.2, string-width@1.0.1, repeating@1.1.3)
├── lodash.camelcase@3.0.1 (lodash._createcompounder@3.0.0)
├── superb@1.1.4 (unique-random-array@1.0.0, meow@3.3.0)
├── slug@0.9.1 (unicode@0.6.1)
├── yeoman-generator@0.20.2 (read-chunk@1.0.1, detect-conflict@1.0.0, yeoman-welcome@1.0.1, path-exists@1.0.0, path-is-absolute@1.0.0, xdg-basedir@1.0.1, yeoman-assert@2.0.0, user-home@1.1.1, rimraf@2.4.2, diff@1.4.0, text-table@0.2.0, mime@1.3.4, dargs@4.0.1, async@0.9.2, istextorbinary@1.0.2, debug@2.2.0, nopt@3.0.3, run-async@0.1.0, mkdirp@0.5.1, shelljs@0.5.1, cli-table@0.3.1, through2@0.6.5, pretty-bytes@1.0.4, dateformat@1.0.11, underscore.string@3.1.1, glob@5.0.14, findup-sync@0.2.1, mem-fs-editor@2.0.4, github-username@2.0.0, cross-spawn@1.0.4, class-extend@0.1.1, download@4.2.0, html-wiring@1.2.0, yeoman-environment@1.2.7, gruntfile-editor@1.0.0, lodash@3.10.0, sinon@1.15.4, inquirer@0.8.5)
└── generator-node@1.3.1 (deep-extend@0.4.0, parse-author@0.2.0, npm-name@1.1.1, lodash@3.10.0, generator-license@2.0.1)

boneskull at lectroid in ~/projects/boneskull/generator-boneskull on master
$ mkdir tmp

boneskull at lectroid in ~/projects/boneskull/generator-boneskull on master
$ cd tmp

boneskull at lectroid in ~/projects/boneskull/generator-boneskull/tmp on master
$ yo boneskull
Error boneskull

You don't seem to have a generator with the name boneskull installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 34 registered generators run yo with the `--help` option.

boneskull at lectroid in ~/projects/boneskull/generator-boneskull/tmp on master
$ yo --version
1.4.7

boneskull at lectroid in ~/projects/boneskull/generator-boneskull/tmp on master
$ npm config get prefix
/usr/local

```

**Comment by boneskull** [comment]
("boneskull" is not listed in `yo --help`)

**Comment by SBoudrias** [comment]
run `yo doctor`

**Comment by SBoudrias** [comment]
Actually, you didn't create an `app` generator. So you don't have `yo boneskull`. You only have `yo boneskull:node`

**Comment by boneskull** [comment]
@SBoudrias thanks!  working now.

**Pull request merged**
